"""Target masking utilities for Supervised Fine-Tuning (SFT).

In instruction tuning and conversational fine-tuning, autoregressive loss
must be computed strictly on the assistant's completion tokens, masking
out prompt tokens (system prompts, user instructions, formatting headers)
with ``IGNORE_INDEX = -100``.  This prevents the model from wasting capacity
memorizing prompts and ensures gradients are only generated by model responses.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Callable, Optional, Sequence, Union

import numpy as np
from numpy.lib import format as npy_format

from .tokenizer import Tokenizer, convert_bin_to_npy

IGNORE_INDEX: int = -100

# Matches assistant response text following an Assistant: or Response: or Completion: header
# (or direct <tool_calls> / <CALL> tags) until the next role turn (User:, System:, Instruction:, Assistant:),
# external tool result (<tool_result>, <RESULT>), or document end (<|endoftext|>, <eos>, $).
_COMPLETION_PATTERN = re.compile(
    r"(?:(?:^|\n)(?:Assistant|Response|Completion):\s*|(?:^|\n)(?=<tool_calls>|<CALL>))(.*?)"
    r"(?=(?:\n(?:User|System|Instruction|Input|Prompt|Assistant):|\n<(?:tool_result|RESULT)|<\|endoftext\|>|<eos>|$))",
    re.DOTALL,
)


def find_completion_spans(text: str) -> list[tuple[int, int]]:
    """Find character spans representing assistant completions in dialogue/instruction text.

    Args:
        text: Training text containing one or more role-tagged turns.

    Returns:
        List of ``(start_char, end_char)`` spans covering assistant response
        text and the trailing ``<|endoftext|>`` or ``<eos>`` delimiter. If no
        role tags are present, returns a single span covering the entire text
        (base pretraining).
    """
    spans: list[tuple[int, int]] = []
    for match in _COMPLETION_PATTERN.finditer(text):
        start = match.start(1)
        end = match.end(1)
        # Include trailing <|endoftext|> or <eos> if immediately following
        tail = text[end:]
        eos_match = re.match(r"\s*(?:<\|endoftext\|>|<eos>)", tail)
        if eos_match:
            end = end + eos_match.end()
        if end > start:
            spans.append((start, end))

    if not spans:
        # No assistant/response delimiters found: treat whole text as target (standard pretraining)
        return [(0, len(text))]
    return spans


def mask_prompt_targets(
    text: str,
    tokenizer: Tokenizer,
    token_ids: Optional[list[int]] = None,
    offsets: Optional[list[tuple[int, int]]] = None,
) -> list[int]:
    """Generate masked target token IDs for an instruction or dialogue text.

    Prompt tokens (system, user, role headers) are set to ``IGNORE_INDEX`` (-100).
    Only tokens within assistant completions (and final EOS) retain their token ID.

    Args:
        text: Document text.
        tokenizer: Tokenizer for token-to-character offset mapping.
        token_ids: Optional precomputed token IDs.
        offsets: Optional precomputed token character offsets.

    Returns:
        List of target IDs of the exact same length as ``token_ids``.
    """
    if token_ids is None or offsets is None:
        encoding = tokenizer.encode(text)
        token_ids = encoding.ids
        offsets = encoding.offsets

    if not token_ids:
        return []

    completion_spans = find_completion_spans(text)
    # If the whole text was returned as one span, no masking is required
    if len(completion_spans) == 1 and completion_spans[0] == (0, len(text)):
        return list(token_ids)

    targets: list[int] = []
    for tid, (off_start, off_end) in zip(token_ids, offsets):
        is_completion = any(
            (s <= off_start < e) or (s < off_end <= e) or (off_start <= s and off_end >= e)
            for s, e in completion_spans
        )
        targets.append(tid if is_completion else IGNORE_INDEX)

    return targets


def encode_file_with_targets(
    tokenizer: Tokenizer,
    corpus_path: Path,
    tokens_output_path: Path,
    targets_output_path: Path,
    tokens_dtype: np.dtype,
    targets_dtype: np.dtype = np.dtype(np.int32),
    should_stop: Optional[Callable[[], bool]] = None,
) -> int:
    """Encode a corpus file to both token IDs and masked target IDs on disk.

    Processes the corpus document-by-document (delimited by ``<|endoftext|>``)
    with bounded memory, saving standard ``.npy`` files for both tokens and targets.

    Args:
        tokenizer: Tokenizer for encoding.
        corpus_path: Path to the corpus text file.
        tokens_output_path: Destination path for ``all_tokens.npy``.
        targets_output_path: Destination path for ``all_targets.npy``.
        tokens_dtype: Integer dtype for tokens (e.g. uint16 or int32).
        targets_dtype: Signed integer dtype for targets (must support -100, int32 default).
        should_stop: Optional callback returning true to cancel.

    Returns:
        Total tokens encoded.
    """
    temp_tokens_bin = tokens_output_path.with_suffix(tokens_output_path.suffix + ".raw_tmp")
    temp_targets_bin = targets_output_path.with_suffix(targets_output_path.suffix + ".raw_tmp")
    tokens_output_path.parent.mkdir(parents=True, exist_ok=True)
    targets_output_path.parent.mkdir(parents=True, exist_ok=True)

    total_tokens = 0
    token_buffer: list[int] = []
    target_buffer: list[int] = []
    flush_threshold = 65536

    try:
        with (
            corpus_path.open("r", encoding="utf-8") as source,
            temp_tokens_bin.open("wb") as tokens_sink,
            temp_targets_bin.open("wb") as targets_sink,
        ):
            doc_lines: list[str] = []
            for line in source:
                if should_stop and should_stop():
                    raise RuntimeError("Dataset preparation stopped by user.")
                doc_lines.append(line)
                if "<|endoftext|>" in line or "<eos>" in line:
                    doc_text = "".join(doc_lines)
                    doc_lines.clear()
                    encoding = tokenizer.encode(doc_text)
                    tids = encoding.ids
                    targs = mask_prompt_targets(doc_text, tokenizer, tids, encoding.offsets)
                    token_buffer.extend(tids)
                    target_buffer.extend(targs)

                    if len(token_buffer) >= flush_threshold:
                        np.asarray(token_buffer, dtype=tokens_dtype).tofile(tokens_sink)
                        np.asarray(target_buffer, dtype=targets_dtype).tofile(targets_sink)
                        total_tokens += len(token_buffer)
                        token_buffer.clear()
                        target_buffer.clear()

            # Process any remaining lines without trailing EOS
            if doc_lines:
                doc_text = "".join(doc_lines)
                encoding = tokenizer.encode(doc_text)
                tids = encoding.ids
                targs = mask_prompt_targets(doc_text, tokenizer, tids, encoding.offsets)
                token_buffer.extend(tids)
                target_buffer.extend(targs)

            if token_buffer:
                np.asarray(token_buffer, dtype=tokens_dtype).tofile(tokens_sink)
                np.asarray(target_buffer, dtype=targets_dtype).tofile(targets_sink)
                total_tokens += len(token_buffer)
                token_buffer.clear()
                target_buffer.clear()

        convert_bin_to_npy(temp_tokens_bin, tokens_output_path, tokens_dtype, total_tokens)
        convert_bin_to_npy(temp_targets_bin, targets_output_path, targets_dtype, total_tokens)
    finally:
        temp_tokens_bin.unlink(missing_ok=True)
        temp_targets_bin.unlink(missing_ok=True)

    return total_tokens


class InstructionDataset:
    """Discrete sample dataset for Supervised Fine-Tuning (SFT).

    Slices the token/target stream by EOS boundary tokens so that each item
    in the dataset is an independent, non-overlapping instruction sample,
    preventing cross-sample contamination and mid-sentence cutting.
    """

    def __init__(
        self,
        tokens: Any,
        targets: Optional[Any] = None,
        context_length: int = 1024,
        eos_token_id: Union[int, Sequence[int]] = 1,
    ) -> None:
        """Create an InstructionDataset.

        Args:
            tokens: Complete token stream.
            targets: Optional parallel target stream (with masked prompt tokens).
            context_length: Maximum allowed sequence length per sample.
            eos_token_id: Token ID (or sequence of token IDs) marking sample end.
        """
        import torch

        self.context_length = context_length
        self.eos_token_id = eos_token_id

        if isinstance(tokens, np.ndarray):
            self._tokens = tokens
        else:
            self._tokens = np.asarray(tokens, dtype=np.int64)

        if targets is not None:
            if len(targets) != len(tokens):
                raise ValueError("tokens and targets must have identical length")
            self._targets = targets if isinstance(targets, np.ndarray) else np.asarray(targets, dtype=np.int64)
        else:
            self._targets = None

        # Identify sample boundaries (each sample ends at any eos_token_id)
        if isinstance(eos_token_id, (list, tuple, set)):
            eos_positions = np.where(np.isin(self._tokens, list(eos_token_id)))[0]
        else:
            eos_positions = np.where(self._tokens == eos_token_id)[0]
        self._sample_ranges: list[tuple[int, int]] = []
        start = 0
        for eos_pos in eos_positions:
            end = int(eos_pos) + 1
            if end - start >= 2:  # Need at least 2 tokens (1 input, 1 target)
                self._sample_ranges.append((start, end))
            start = end
        if start < len(self._tokens) and (len(self._tokens) - start >= 2):
            self._sample_ranges.append((start, len(self._tokens)))

        # Fallback: if no EOS tokens found, treat as single sample
        if not self._sample_ranges and len(self._tokens) >= 2:
            self._sample_ranges.append((0, len(self._tokens)))

    def __len__(self) -> int:
        return len(self._sample_ranges)

    def __getitem__(self, index: int) -> tuple[Any, Any]:
        import torch

        start, end = self._sample_ranges[index]
        sample_len = min(end - start, self.context_length + 1)
        tok_slice = np.asarray(self._tokens[start : start + sample_len], dtype=np.int64)
        input_ids = torch.from_numpy(tok_slice[:-1])

        if self._targets is not None:
            targ_slice = np.asarray(self._targets[start : start + sample_len], dtype=np.int64)
            target_ids = torch.from_numpy(targ_slice[1:])
        else:
            target_ids = torch.from_numpy(tok_slice[1:])

        return input_ids, target_ids


def collate_instruction_batch(
    batch: list[tuple[Any, Any]],
    pad_token_id: int = 0,
) -> tuple[Any, Any]:
    """Collate and dynamically pad a batch of variable-length instruction samples.

    Pads inputs with ``pad_token_id`` and targets with ``IGNORE_INDEX`` (-100)
    up to the maximum sequence length present in the batch.

    Args:
        batch: List of (input_ids, target_ids) tuples.
        pad_token_id: Token ID used for input padding.

    Returns:
        Tuple of (batch_inputs, batch_targets) of shape (batch_size, max_seq_len).
    """
    import torch

    max_len = max(len(x) for x, _ in batch)
    padded_inputs: list[torch.Tensor] = []
    padded_targets: list[torch.Tensor] = []
    for x, y in batch:
        pad_len = max_len - len(x)
        if pad_len > 0:
            x_pad = torch.cat([x, torch.full((pad_len,), pad_token_id, dtype=x.dtype)])
            y_pad = torch.cat([y, torch.full((pad_len,), IGNORE_INDEX, dtype=y.dtype)])
        else:
            x_pad = x
            y_pad = y
        padded_inputs.append(x_pad)
        padded_targets.append(y_pad)
    return torch.stack(padded_inputs), torch.stack(padded_targets)

